#
# ProcProtect Driver Makefile
# WDK 10/11 MSBuild 入口
#
# 用法: 在 "x64 Native Tools Command Prompt for VS 2022" 中运行:
#   msbuild /p:Configuration=Release /p:Platform=x64
#
!INCLUDE $(NTMAKEENV)\makefile.def
